# Generated by Django 5.0.6 on 2025-11-12 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor')], default='comprador', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Imagen de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
