# Generated by Django 5.2.8 on 2025-12-06 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria_alter_producto_precio_and_more'),
        ('usuarios', '0002_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('reviewer', 'producto'), name='unique_reviewer_producto'),
        ),
    ]
