# Generated by Django 5.2.8 on 2025-11-23 22:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_alumnos_options_alumnos_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('comentario', ckeditor.fields.RichTextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario contacto',
                'verbose_name_plural': 'Comentarios contactos',
                'ordering': ['-created'],
            },
        ),
    ]
