# Generated by Django 5.0.6 on 2025-11-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, choices=[('azul', 'Azul'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('negro', 'Negro'), ('blanco', 'Blanco'), ('amarillo', 'Amarillo'), ('rosa', 'Rosa'), ('morado', 'Morado'), ('naranja', 'Naranja'), ('gris', 'Gris'), ('marrón', 'Marrón'), ('turquesa', 'Turquesa')], max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='Tamaño'),
        ),
    ]
