# Generated by Django 5.2.8 on 2025-12-06 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_color_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('electronicos', 'Electrónicos'), ('muebles', 'Muebles'), ('libros', 'Libros'), ('accesorios', 'Accesorios'), ('otros', 'Otros')], help_text='Selecciona la categoría que mejor describe el producto.', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Introduce el precio en MXN, mayor que 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(help_text='Ej: Camisa de algodón talla M', max_length=200, verbose_name='Título'),
        ),
    ]
